### PR TITLE
remove grunt dependencies

### LINKED ISSUE #25: remove grunt dependencies
## Issue description

The grunt dependencies should exist any longer.

### PR DESCRIPTION
**Pull request by Ma27**
Resolves #25 
### Whats new:
- remove grunt dependencies
- create .sailsrc which disables grunt on sails.js

### CODE REVIEW

**Comment by Ma27** [comment]
@benbieler Please review this - works for me, the app starts successfully with the changes in that branch...

**Comment by benbieler** [comment]
@ma27 I know. I did exactly the same thing in my commit about 2 weeks ago. The problem is that sails has a .tmp directory wich has to stay in sync. True that the server starts. But you won't see any changes you have made...

**Comment by benbieler** [comment]
https://github.com/SocialDocs/SocialDocs/blob/%232-user-management/.sailsrc

**Comment by benbieler** [comment]
Please just wait until #16 is finished. A lot of the current fuck ups will be resolved.

**Comment by Ma27** [comment]
of course I'll wait!
But I hope that this is know sails bug. I'd attempt to separate the frontend from the backend (if possible) in order to do you what we'd like to do and not that what sails forces us to.

**Comment by benbieler** [comment]
Great😉

**Pull request closed without merging**
